version: '3.8'

services:
  dind:
    container_name: dind
    image: docker:24-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    entrypoint: /usr/local/bin/boot-dind.sh
    ports:
      - "2375:2375"
      - "3306:3306"
      - "6379:6379"
    volumes:
      - ./boot-dind.sh:/usr/local/bin/boot-dind.sh:ro
